# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Felix < Formula
  desc "let felix fix it"
  homepage "https://alchemain.com"
  version "0.2.9"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alchemain/felix/releases/download/v0.2.9/felix_0.2.9_Darwin_x86_64.tar.gz"
      sha256 "a43390a9cfe1980614b8860f847fad7f6da3d595aa27aefc9a4c517414b5693d"

      define_method(:install) do
        bin.install "felix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alchemain/felix/releases/download/v0.2.9/felix_0.2.9_Darwin_arm64.tar.gz"
      sha256 "27a80937efa13efdbf008f2cb55e2343b5696d2fbea562bbefe987c42ffa2a65"

      define_method(:install) do
        bin.install "felix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemain/felix/releases/download/v0.2.9/felix_0.2.9_Linux_x86_64.tar.gz"
      sha256 "6e619149c673725f33735134587a5f32645ff9546d6d75093c1dd57bbb9b6f4d"
      define_method(:install) do
        bin.install "felix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemain/felix/releases/download/v0.2.9/felix_0.2.9_Linux_arm64.tar.gz"
      sha256 "3f9c812d7e2a74300958f5209e4b29abf83cd69362557fea8738127c0dafd121"
      define_method(:install) do
        bin.install "felix"
      end
    end
  end

  test do
    system "#{bin}/felix"
  end
end
