# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Felix < Formula
  desc "let felix fix it"
  homepage "https://alchemain.com"
  version "0.2.11"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alchemain/felix/releases/download/v0.2.11/felix_0.2.11_Darwin_x86_64.tar.gz"
      sha256 "4a283eb6d411f561ee637d3be3837f039c00d8a7207fa5b028da75dd0200b10e"

      define_method(:install) do
        bin.install "felix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alchemain/felix/releases/download/v0.2.11/felix_0.2.11_Darwin_arm64.tar.gz"
      sha256 "f675d9cd0d073dc7dcffa074cac51d5eeaab56521bb1b312a4c5f0346776730a"

      define_method(:install) do
        bin.install "felix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemain/felix/releases/download/v0.2.11/felix_0.2.11_Linux_x86_64.tar.gz"
      sha256 "b26c48289a3cd358d9ccf99e891f6c1c11781569cad9e23b2ed3fe3a826ce635"
      define_method(:install) do
        bin.install "felix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemain/felix/releases/download/v0.2.11/felix_0.2.11_Linux_arm64.tar.gz"
      sha256 "1921598287364a3b031c3444de1c0147c32ee7a15756c3e4371ed2f87f424a77"
      define_method(:install) do
        bin.install "felix"
      end
    end
  end

  test do
    system "#{bin}/felix"
  end
end
